### ISSUE TITLE
Support for non-Markdown READMEs?

### ISSUE THREAD

**Issue by dstu** [rust-lang/docs.rs#101]
I've been in the habit of using org-mode for markup in my project README files. (Github renders them adequately, so it hasn't been an issue so far.) But docs.rs isn't rendering org-mode content correctly (https://docs.rs/crate/symbol-map/1.0.0). Is support for non-Markdown READMEs planned or in the works? I don't see evidence of a Rust renderer org-mode on the Web, so I presume the answer in the case of org-mode is "no."

**Comment by jyn514** [comment]
We do not have non-markdown support planned, no. I'm a little wary of adding support for more file formats because that raises the question where to stop (we can't possibly support every file format in existence). There would also have to be an existing rust library for converting the file format to HTML. Note that crates.io also only supports markdown (https://github.com/rust-lang/crates.io/issues/1223).

I would be willing to take a PR for this but I don't plan to implement it any time soon.

**Comment by jyn514** [comment]
https://github.com/rust-lang/crates.io/issues/1223 was closed:

> Since documentation comments in Rust only support Markdown I think it's reasonable for us to also only support Markdown. Other formats are now displayed as plain text so basic support exists, but implementing more than that would increase the complexity quite a bit and that doesn't not seem like something we will implement in the near future.

That reasoning makes sense to me, so I don't think docs.rs needs to support other formats of READMEs.
