### ISSUE TITLE
SIGKILL (OOM?) for documenting web-sys 0.3.46

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/docs.rs#1197]
**Crate name:** web-sys
**Build failure link:** https://docs.rs/crate/web-sys/0.3.46/builds/321002

**Additional details:**

Is it possible to figure out why SIGKILL was received on this build? I think that OOM is the obvious suspect since this is a huge crate with all of its documentation enabled (which we do for docs-rs). I wanted to ideally confirm though that this was OOM-killed before trying to do something else.

Otherwise, if the memory limit can't be raised, I suspect the next step is to open a bug on rustdoc itself!

**Comment by jyn514** [comment]
> Is it possible to figure out why SIGKILL was received on this build?

Not without running `cargo doc` or a local docs.rs instance, unfortunately - I'd love to have it though: https://github.com/rust-lang/docs.rs/issues/878.

I can definitely raise the memory limit in the meantime, it will probably be a while before rustdoc's memory consumption improves (although if the cause is different here than in https://github.com/rust-lang/rust/issues/79103 I'd love to hear about it :slightly_smiling_face:)

**Comment by jyn514** [comment]
```
$  command time -v cargo doc --all-features
	Maximum resident set size (kbytes): 3117768
```
Yup, this *just* hit the limit. I'll bump it to 5 GB for now, that should be enough for a while.

**Comment by jyn514** [comment]
Requeued and rebuilt: https://docs.rs/crate/web-sys/0.3.46

**Comment by alexcrichton** [comment]
Thanks!
