### ISSUE TITLE
crassipes-0.2.0 build failure

### ISSUE THREAD

**Issue by drdeaton** [rust-lang/docs.rs#1299]
**Crate name: Crassipes**
**Build failure link: https://docs.rs/crate/crassipes/0.2.0/builds/355997**

**Additional details:** Its failing to build because a dependency, crs-bind, which is based directly on the crate vex-rt (which does build) isn't able to build due to code that is present in the original vex-rt crate. The documentation builds and displays fine both on my local machine and in Gitlab CI. [crs-bind also builds and documents fine on its own.](https://docs.rs/crs-bind/0.1.3/crs_bind/)

**Comment by jyn514** [comment]
@Dysproh can you replicate this failure locally?

**Comment by Dysproh** [comment]
No

**Comment by jyn514** [comment]
@Dysproh do you have a lockfile, maybe? I suspect there's a transitive dependency that changed.

**Comment by Dysproh** [comment]
the lockfile being cargo.lock? From which project?

**Comment by Nemo157** [comment]
The build log looks odd to me, why is it `Compiling crs-bind` rather than just `Checking` it, it's a non-build dependency.

**Comment by Dysproh** [comment]
it has to run bindgen to create ffi bindings. Is there a better way to do this?

**Comment by Nemo157** [comment]
The error is valid on some platforms and unrelated to the build-script or generated code.

In `ptr::copy(cstring, s.as_mut_ptr(), len);` the `cstring: *const c_char` and `s: String`, the `String` always has a `u8` buffer while `c_char` is either `i8` or `u8` depending on platform.

`cargo build --target x86_64-pc-windows-msvc` fails similarly for me in `crs-bind`, I'm not sure why the default linux build failed since afaik that should be a `u8` using platform, or why the `crs-bind` doc build itself succeeded for `-msvc` 😕

**Comment by Dysproh** [comment]
Thats interesting. Anyway, these crates should only be built ever for `armv7a-vex-eabi`, which is just `armv7a-none-eabi` afaik. Is there any way to make docs.rs only target that platform?

**Comment by Nemo157** [comment]
See the `targets` section in https://docs.rs/about/metadata

**Comment by Dysproh** [comment]
I tried using `targets = ["armv7a-vex-eabi.json]` but now its giving me this: https://docs.rs/crate/crs-bind/0.1.5/builds/357704

**Comment by Nemo157** [comment]
The `.cargo/config` is stripped before the build, so `-Zbuild-std` isn't used, there's also no currently no way to pass custom arguments to `cargo` during the build.

@jyn514 do you think it might be appropriate to add `cargo-args` to the metadata in order to support flags like `-Zbuild-std=std,alloc` like this build would need?

**Comment by jyn514** [comment]
Sure, cargo-args seems useful.

**Comment by jyn514** [comment]
`cargo-args` was added in https://github.com/rust-lang/docs.rs/pull/1374, so you can start using `-Z build-std` now if you like.

**Comment by syphar** [comment]
From my understanding, this could be solved with https://github.com/rust-lang/docs.rs/pull/2107?
