### ISSUE TITLE
Document that system dependencies are ignored

### ISSUE THREAD

**Issue by sfackler** [rust-lang/docs.rs#164]
I thought I had configured docs.rs correctly to install an extra system dependency, but it doesn't seem to have worked:

https://github.com/sfackler/rstack/blob/master/unwind-sys/Cargo.toml#L14
https://docs.rs/crate/unwind-sys/0.1.0/builds/75612

Any idea what's going on there?

**Comment by sfackler** [comment]
As far as I can tell, that field isn't actually used anywhere...

**Comment by onur** [comment]
Yes, installing system dependencies is not a thing ATM and I am not sure it will be in future. I was planning to switch to a docker based build system and use a plain image and `dependencies` to install whatever needed similar to travis. But it will just cause more headache, people have to maintain correct dependencies all the time and it may be tricky in Debian. And there is no testing suite for docs.rs, even with current simple metadata section, people are forced to upload a new version if they mess up metadata. Because of this I didn't want to implement system dependencies and trying to keep docs.rs as simple as possible.

**Comment by pkgw** [comment]
It would be helpful to update the documentation to indicate that `dependencies` doesn't do anything at the moment.

**Comment by jyn514** [comment]
This was never documented and is no longer in the code at all.
