### ISSUE TITLE
Replace custom `index::crates::Crates` with `crates_index::Crates`

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#1661]
After the upgrade in #1660 the comment here is out of date:

https://github.com/rust-lang/docs.rs/blob/5c3b6898c34add186661b34ad0c6e947e9380a86/src/index/mod.rs#L97-L100

The new version of `crates_index` supports bare repositories so we should be able to use it directly.

**Comment by jyn514** [comment]
@Nemo157 hmm, I'm not quite sure I follow - I don't see a way to walk the repo in https://docs.rs/crates-index-diff/latest/crates_index_diff/struct.Index.html, you have to know the initial commit ahead of time. And we can't hard-code the commit because it can change when crates.io squashes the index: https://github.com/rust-lang/crates.io-index/commit/dcb14b9012f15cf806bd0a61c982e9d6f76a7d63

**Comment by Nemo157** [comment]
<https://docs.rs/crates-index/latest/crates_index/>, not `crates-index-diff`. That is the library we use to parse the point-in-time index to compare what is in the database against. Back when that was first implemented its iterator worked off the files in a checked out working directory, but since then has been updated to work directly off git objects.
