### ISSUE TITLE
Failed to compile docs due to symbol not found

### ISSUE THREAD

**Issue by kittuov** [rust-lang/docs.rs#1786]
### Crate name

dxfilter

### Build failure link

https://docs.rs/crate/dxfilter/0.5.8/builds/602755

### Additional details

The build fails saying that Some symbol is not available in the macro crate. but the macro crate successfully compiled on docs.rs. It compiles successfully locally too.

**Comment by Nemo157** [comment]
`shader-macro`'s docs were able to be generated because it doesn't need to link against the windows APIs while generating docs. To actually run the macro while generating the docs for `dxfilter` it does need to run. Unfortunately there is no way to run code that relies on windows functions as we always cross-compile from linux. The only workaround I could suggest is to guard all the shader related code with `#[cfg(not(doc))]` so that you don't attempt to load or run the proc-macro while generating docs.

**Comment by kittuov** [comment]
That fixed the issue for me. I imported dummy method for docs and it’s compiling now
