### ISSUE TITLE
Build failure due to yanked crate

### ISSUE THREAD

**Issue by WalterSmuts** [rust-lang/docs.rs#1854]
### Crate name

easyfft

### Build failure link

https://docs.rs/easyfft/latest/easyfft/

### Additional details

Not sure how to link to the build failure itself so I provided the latest web-link. Note that it points to `0.2.0` and that [crates.io](https://crates.io/crates/easyfft/versions) shows version `0.2.2`.

The build failure was [almost definitely] caused by depending on a crate that I own, which had the version yanked. I subsequently unyanked that crate so another build should pass.

Is there a way of solving this for the general case? I.e. allow users to re-submit builds or some such. I guess such a button would get abused.

On a separate note, the reason I originally yanked the crate is because it is unsound in the general case. I know that it's not unsound in the way that `easyfft` uses it so I haven't updated to the newer (slower) sound version. I misunderstood how yanked crates work (I thought easyfft would still compile) but looks like the behaviour is to deny anyone without a `Cargo.lock` file already. I suspect the correct course of action is to just copy the unsound "fast" version of the crate into `easyfft` as a module. Let me know if there are better options.

**Comment by Nemo157** [comment]
You could publish the `Cargo.lock` along with your library and docs.rs will attempt to build with it first. AFAIK there's no option to force it to be included, but if you have any binary crate (a `[[bin]]` or `[[example]]`) then cargo will include it into the package automatically.

**Comment by Nemo157** [comment]
Rebuild is queued.

**Comment by WalterSmuts** [comment]
Thanks! It's up and running :)

Also, I read up about the `Cargo.lock` usage and [the faq  on why it's a bad idea in libraries](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) makes sense. I would be locking a bunch of other library versions too, which is not desirable. I wish I could specify in the `Cargo.toml` that "yes I really want this specific version, even if it is yanked". Will think a bit more about it and start a discussion if I'm more sure of the idea.

Feel free to close the issue :)

**Comment by WalterSmuts** [comment]
> Will think a bit more about it and start a discussion if I'm more sure of the idea.

Perhaps a `Cargo.lock.override` file might work. But feels like we're getting a bit far into the weeds here.

**Comment by Nemo157** [comment]
Publishing a lockfile doesn't affect your dependents, it only applies when building your crate as the root of the build-tree (such as when docs.rs builds it). IMO all libraries should have committed lockfiles so that things like `git bisect` are resilient to yanked dependencies, and similar reasoning applies to publishing the lockfile in the package. It just takes a little more work setting CI up to also attempt updating and running a build against the latest allowed versions.

(docs.rs is also resilient against a broken published lockfile as seems to happen far too often, if building with the lockfile fails we delete it and try again).
