### ISSUE TITLE
Is it possible to increase a README character limit?

### ISSUE THREAD

**Issue by zhiburt** [rust-lang/docs.rs#1866]
### Crate name

tabled

### Build failure link

https://docs.rs/crate/tabled/0.9.0

### Why your crate needs the resource increases

Hi there,

Yes....
I guess someone need to redo the README but is it possible to increase the limit?

Take care.

**Comment by jyn514** [comment]
I think we should consider just removing the limit; I don't know why it was added in the first place, but we don't limit the size of the pages rustdoc generates, so I don't know why we'd limit readmes either.

**Comment by Nemo157** [comment]
There is a limit on rustdoc pages too, it's just (at least by default) a lot more lenient

https://github.com/rust-lang/docs.rs/blob/b5451e0f4df0491b50d24932c585b0771a595a1f/src/config.rs#L133-L134

I think the problem is the readme is [stored in the database](https://github.com/rust-lang/docs.rs/blob/b5451e0f4df0491b50d24932c585b0771a595a1f/src/db/add_package.rs#L48) instead of being sourced from S3. I remember some discussion on storing the source archive even when the build fails but can't find the issue (related to https://github.com/rust-lang/docs.rs/issues/1011 though), once we have that then I think we can change to rendering from the source file instead of the database column which will implicitly remove the length restriction.

**Comment by jyn514** [comment]
> (We could change to going to S3 when the source archive is available now, though that wouldn't help in this case because the build also failed).

We upload the source archive even when the build fails, that shouldn't impact anything. I agree that's a good solution and would let us use the same limit for the readme as everything else (and as a bonus make the database a lot smaller).

**Comment by Nemo157** [comment]
Ah yeah, that explains why I couldn't find the issue, it was already closed https://github.com/rust-lang/docs.rs/issues/607. We'll still need to read the database as a backup for crates that built before that was fixed until the mass rebuild.
