### ISSUE TITLE
Change static root path

### ISSUE THREAD

**Issue by jsha** [rust-lang/docs.rs#1869]
Right now, docs.rs passes `--static-root-path=/` to rustdoc, and static files are served directly from the docs.rs root, e.g. https://docs.rs/storage-20220709-1.64.0-nightly-6dba4ed21.js.

It would be aesthetically pleasing if these static files had their own directory. For instance, we could pass `--static-root-path=/rustdoc.static/`, and simultaneously change the storage path at which we upload these files to be `/rustdoc.static/`. Then static files would be served from URLs like `https://docs.rs/rustdoc.static/storage-20221225-1.68.0-nightly-abc1234567.js.

This does not require any coordinated changes from rustdoc. We could do it today. It happens to harmonize with (but not depend on) https://github.com/rust-lang/rust/pull/101702, which envisions a similar change rustdoc's default output, where static files are put in their own directory.

It _does_ depend on a tweak to how we serve static files, specifically SharedResourceHandler: https://github.com/rust-lang/docs.rs/blob/802fd8e024f5fc89fc0a69e65fa918513ca83184/src/web/rustdoc.rs#L726-L749

SharedResourceHandler considers only the last component of a URL's path when serving `["js", "css", "woff", "woff2", "svg", "png"]`. We could add a small bit of extra logic: If a URL's path begins with `/rustdoc.static`, consider the full path.

**Comment by syphar** [comment]
we should definitely change the static path root. This the namespace overlaps with crate-names we typically try to use a `/-/` prefix for our internal paths where possible. 

IMO the storage location doesn't necessarily have to be the same / have the same name. 

I agree that https://github.com/rust-lang/rust/pull/101702 doesn't affect the static root path or the static file location. 

In general I would have loved to have split the storage for static files by nightly release so we don't have everything in one folder, but that would break the shared caching of these since the prefix would have to include the nightly version. 
Same as having a static file archive by nightly, which would ease the download but make caching / serving these harder.

**Comment by syphar** [comment]
@jsha I was trying to prepare a branch doing the change, and a question about https://github.com/rust-lang/rust/pull/101702 came to me: 

Will the static files be moved to a subfolder as you described? 

To me it looks like our current build process would then also copy them to a subfolder onto our S3 bucket, which also means `SharedResourcesHandler` wouldn't pick them up since it only looks at the filename, ignoring any folder. 

So from a pure docs.rs perspective the easier approach would be not to move the static assets in rustdoc. 

We can still serve them through providing another `static-root-path`

**Comment by jsha** [comment]
Oh great! I had started on a branch (https://github.com/jsha/docs.rs/pull/new/static-new-path) but if you can finish it out that's great. The branch I have still needs a new route handler.

> To me it looks like our current build process would then also copy them to a subfolder onto our S3 bucket, which also means SharedResourcesHandler wouldn't pick them up since it only looks at the filename, ignoring any folder.

Yes. Here's my idea: the `/-/rustdoc.static/` files wouldn't rely on SharedResourcesHandler. Instead they would rely on a more traditional route handler for that path that serves from S3 in the "normal" way (including paths).

> So from a pure docs.rs perspective the easier approach would be not to move the static assets in rustdoc.

Here's my reasoning on putting them in a subfolder by default in rustdoc: Some of the past bugs in static asset handling were related to confusion about the doc root vs the static asset root, because they are the same by default. Making them different by default makes it much easier to understand what's going on and makes bug less likely.

This is indeed awkward for the transition moment. Here's what I propose: If the docs.rs builder sees a target/doc/static.files/ folder, it copies those contents as the static root; otherwise it copies target/doc/ as the static root. Then once https://github.com/rust-lang/rust/pull/101702 is released we can remove the logic and always copy target/doc/static.files/.

**Comment by jsha** [comment]
I updated https://github.com/jsha/docs.rs/pull/new/static-new-path and it now has a route-based handler. I had to comment out a different route to make it work. Clearly something is going on with priority and specificness of routes, but I couldn't figure out what or how to fix it so far. Putting my handler above or below the other handler doesn't seem to change things.

```
    routes.static_resource("/-/rustdoc.static/*", super::rustdoc::SharedResourceHandler2);
//    routes.rustdoc_page(
//        "/:crate/:version/:target",
//        super::rustdoc::rustdoc_redirector_handler,
//    );
```

**Comment by syphar** [comment]
Having slept over it, and read your comment, having a subdirectory from rustdoc for static assets is probably cleaner than the current situation. 

IMO `add_essential_files` then only should look at this static-file folder and not copy everything as it does right now. 

So when we are sure about the change in rustdoc, we should prepare docs.rs for it.

**Comment by jsha** [comment]
Great! Meanwhile I figured out the routing issue on my branch-in-progress (needed to add a route for `/-/rustdoc.static/:single`, because it appears Iron considers that more specific?).
