### ISSUE TITLE
Crate dependency build failed due to dns resolution

### ISSUE THREAD

**Issue by mdrokz** [rust-lang/docs.rs#2018]
### Crate name

headless_chrome

### Build failure link

https://docs.rs/crate/headless_chrome/1.0.1/builds/713766

### Additional details

Hi im a maintainer of headless_chrome and headless_chrome uses a build dependency [auto_generate_cdp](https://crates.io/crates/auto_generate_cdp/0.4.0) it hits an API request to https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/js_protocol.json and the build fails due to DNS resolution of the domain name.

refer to https://github.com/rust-lang/crates.io/issues/6002 & https://github.com/atroche/rust-headless-chrome/issues/355

**Comment by Nemo157** [comment]
Docs are built in a sandbox with no network access <https://docs.rs/about/builds#hitting-resource-limits>. Preferably the json file for the protocol would be bundled in the crate files so that it can build without having internet. Alternatively you might be able to [detect when running on docs.rs](https://docs.rs/about/builds#detecting-docsrs) and not download the file, and use `#[cfg(not(doc))]` to not attempt compiling code that depends on it, if your API is able to be described without it.

**Comment by mdrokz** [comment]
> Docs are built in a sandbox with no network access https://docs.rs/about/builds#hitting-resource-limits. Preferably the json file for the protocol would be bundled in the crate files so that it can build without having internet. Alternatively you might be able to [detect when running on docs.rs](https://docs.rs/about/builds#detecting-docsrs) and not download the file, and use `#[cfg(not(doc))]` to not attempt compiling code that depends on it, if your API is able to be described without it.

Thanks for replying, Ok that makes sense i will see my options thanks
