### ISSUE TITLE
Bindgen generated C bindings library fails to build

### ISSUE THREAD

**Issue by OWissett** [rust-lang/docs.rs#2029]
### Crate name

freesasa-sys

### Build failure link

https://docs.rs/crate/freesasa-sys/0.1.8/builds/736123

### Additional details

The docs can be built locally, however, it is not working on docs.rs. I have tried using the c_plusplus crate, which is meant to add allow for the use of libstdc++ and libc++ to rust programs, but this isn't working.

The is a C library which is built using autotools from source and rust bindings are generated by bindgen.

The build is failing, since it is not able to link the C++ standard library (which is required for building the C library). I am not the author of C library.

The C library is: https://freesasa.github.io/

**Comment by syphar** [comment]
You can find more about how our build works on this page: https://docs.rs/about/builds#missing-dependencies 

Specifically, missing dependencies need to be added to [`crates-build-env`](https://github.com/rust-lang/crates-build-env). 

We also see crate authors vendoring the header-files and/or special-casing docs.rs for the build, since often the actual C library is not needed only to provide the docs.

**Comment by syphar** [comment]
Hi @OWissett 

I'm closing this issue now, feel free to reopen it if this still a problem / the information above isn't enough.
