### ISSUE TITLE
add funding link for maintaining the availability of docs.rs

### ISSUE THREAD

**Issue by spacejam** [rust-lang/docs.rs#203]
This is in response to #202 taking a little time to be addressed.

This is an awesome thing, and has become an important piece of infrastructure for the rust community. I'm certain I'm not alone in being willing to throw a few bucks per month at the project to help keep it awesome. Maintainers should feel real support from their users, not just a sense of guilt to keep something running on their behalf.

On the README there's this snippet:
`If you are interested in sponsoring Docs.rs, please don't hesitate to contact us at TODO.`

If this changes to a link to patreon, gratipay, liberapay, bountysource, open source collective, buy me a coffee, or whatever else works well for the project, I'd be happy to throw in some support.

Thanks for making this wonderful tool for the rust community!

**Comment by QuietMisdreavus** [comment]
The Rust project has started to absorb docs.rs as an official project, starting with adding onur to the new [Rustdoc team](https://www.rust-lang.org/en-US/team.html#Rustdoc-team). My personal hope for the end-game of this would be to put maintenance of docs.rs alongside the other Rust infrastructure: sponsorship by Mozilla (or continued sponsorship by Leaseweb, as it seems to be right now), operations assisted by the Rust Infrastructure team, increased community contributions to docs.rs as a platform thanks to its management by an official subteam.

Hopefully this helps!

**Comment by mati865** [comment]
@QuietMisdreavus are there any news about ongoing effort?
Don't get me wrong, I'm not asking for ETA or demanding anything. It's a wonderful project but it's "corroding" and getting to the point where updated crates don't build at all.

**Comment by QuietMisdreavus** [comment]
Update: For the last few months, docs.rs has been hosted on a server managed by the Rust Infrastructure Team. Any interest in funding, donations, or sponsorship can be directed to the Rust Project as a whole. Maintainership is still on a volunteer basis, but at least the server hardware is being managed by more than one person. As such, i'm going to close this issue. If you're interested in sponsoring the server for docs.rs, please contact the Infrastructure Team.

(if you're interested in small-scale recurring donations to the *operations* of docs.rs, i personally have a Patreon, but i'm not going to link it here, since it's just for one person, not the team as a whole.)
