### ISSUE TITLE
Error when compiling libduckdb-sys v0.7.1

### ISSUE THREAD

**Issue by angelip2303** [rust-lang/docs.rs#2103]
### Crate name

pregel-rs

### Build failure link

https://docs.rs/crate/pregel-rs/0.0.1/builds/789566

### Additional details

Hi! I have a building issue when compiling `libduckdb-sys v0.7.1`, a dependency of my project. If I generate the docs locally everything works just fine, so I don't really know what's going wrong :(. It is my first time publishing to docs.rs so I'm quite a newbie here :D, and to the Rust ecosystem in general,. Any advice is well appreciated. The only thing that I can point out is the limited amount of resources, but as I mentioned, I don't really know.

**Comment by Nemo157** [comment]
"killed" means out-of-memory, there's a default 3GB memory limit for the build. I've bumped the limit to 6GB for `pregel-rs` and queued another build (https://docs.rs/releases/queue), but I would recommend removing the `bundled` feature so that it will not attempt to build the C++ library which takes all the time/memory (and is not something a library should be activating, that feature is intended for final applications to use).

**Comment by Nemo157** [comment]
Looks like 6GB is also not enough, you'll have to publish another version without the `bundled` feature active.

**Comment by angelip2303** [comment]
Perfect, I am already working on it!

**Comment by angelip2303** [comment]
Issue solved :D, version 0.0.2 is now online! Thanks for the support!
