### ISSUE TITLE
cowstr failed to build on crates.io because of network error

### ISSUE THREAD

**Issue by cehteh** [rust-lang/docs.rs#2122]
### Crate name

cowstr

### Build failure link

https://docs.rs/crate/cowstr/1.0.0-beta2/builds/804480

### Additional details

looks there was some network glitch, can you restart doc generation?

[6] Couldn't resolve host name (Could not resolve host: index.crates.io)

**Comment by Nemo157** [comment]
Yeah, I'm not entirely sure why cargo's attempting to access the network here, afaik both builds should have been using the new sparse registry protocol since that [was merged](https://github.com/rust-lang/cargo/pull/11791) back in march, so it's not to do with that behaving differently. Using `--offline` should hopefully avoid it.

**Comment by cehteh** [comment]
On 2023-05-03 12:16, Nemo157 wrote:

>Yeah, I'm not entirely sure why cargo's attempting to access the
>network here, afaik both builds should have been using the new sparse
>registry protocol since that [was
>merged](https://github.com/rust-lang/cargo/pull/11791) back in march,
>so it's not to do with that behaving differently. Using `--offline`
>should hopefully avoid it


i am first improving conf_test its was once made as an hack and i
recently using it again. It certainly needs some fixes.

**Comment by syphar** [comment]
@cehteh @Nemo157 I see the latest beta-builds are passing now. 

So is this still an open issue here?

**Comment by cehteh** [comment]
all ok now i changed a lot stuff in the crate
