### ISSUE TITLE
There is to be a way to conveniently identify and perhaps offer fixes to documentation

### ISSUE THREAD

**Issue by gdennie** [rust-lang/docs.rs#2142]
The docs are not perfect. Some of the issues are obvious typos but others include convoluted phrasing and treatment of subject. Presently, there is no obvious way to report or suggest changes. That is a problem and a massive opportunity lose given the talents of the community. It is a lot easier to review and accept a change than to construct one.

**Comment by syphar** [comment]
Hi, 

I definitely like the idea. 

How do you imagine this could look like concretely?

**Comment by gdennie** [comment]
Firstly, a voting system would help flag particularly problematic but frequently accessed pages.

Secondarily,  an `edit button` on each page that takes you to the actual editable document on github so that github's pull request process can be used conveniently to submit improvement suggestions.

**Comment by Nemo157** [comment]
An edit button makes most sense as a rustdoc feature, probably by being able to pass some "edit-url-template" that gets filled out with the manifest-relative source file etc. (to support non-github and workspaces). Voting seems more difficult, I don't know where the data would be stored and how it would get shown to the developers.

**Comment by syphar** [comment]
edit-url sounds awesome, though tricky. 

Docs.rs shows a released version, and most of the time edits would happen on the main branch of the repo. 

@Nemo157 but this sounds like this is likely a rustdoc change, not docs.rs? 

So we could move this issue?

**Comment by gdennie** [comment]
I suppose the vote count could be stored as a page element and possibly displayed.

**Comment by gdennie** [comment]
> edit-url sounds awesome, though tricky.
> 
> Docs.rs shows a released version, and most of the time edits would happen on the main branch of the repo.
> 
> @Nemo157 but this sounds like this is likely a rustdoc change, not docs.rs?
> 
> So we could move this issue?

It is an issue that affects the utility of Docs.rs. Perhaps `rustdoc` has become inadequate, a bottleneck. In any event,  ignoring this issue of effectfulness can't be a good option.

**Comment by syphar** [comment]
> This issue affects the utility of Docs.rs. 

Not only docs.rs, this also affects users that build the docs of other crates locally themselves. Which is a valid use-case for docs. 

> Perhaps current `rustdoc` has become inadequate, a bottleneck. In any event, ignoring this issue shouldn't be an option. Perhaps these two products are too interdependent.

Even without the rustdoc/docs.rs split, this would not be an easy or simple topic, taking all the different kinds of crates and how each builds its docs into account. 

Personally I'm not sure how voting would help improve the docs, while having an easy way to create issues on the crates' repo, or directly get to the source-file, would definitely make improvements easier. 

Since both features would need rustdoc changes, the next step (if you want to take it) is probably an initial design discussion on the https://github.com/rust-lang/rust repo (where rustdoc lives), or on https://internals.rust-lang.org/ . 

cc @GuillaumeGomez

**Comment by gdennie** [comment]
**Voting** would identify particularly good documentation and flag particular bad ones with an emphasis on those that are heavily used. It informs the author and potentially provides good, bad examples, and good changes. I suppose instead of a vote it may better be described or become a **survey** seeing that it would be useful if voters could also provide a rating on their personal experience level with Rust, the API, and perhaps other Rust API's, etc.

**Comment by GuillaumeGomez** [comment]
I'm not sure to see how voting would help here. It'd just be a way to flag some documentations as bad and that's pretty much where it would stop in my opinion. So not improving in any way.

It was mentioned that there was no easy way to help improve a documentation, but what's preventing users to open an issue on the repository directly?

**Comment by GuillaumeGomez** [comment]
Also cc @jsha and @Manishearth.

**Comment by gdennie** [comment]
Lack of knowledge is what is preventing users from opening an issue with the underlining repository directly. Lack of knowledge is also why they come to the documentation in the first play. The UI of the documentation presentation needs to be improved.

**Comment by GuillaumeGomez** [comment]
> Lack of knowledge is what is preventing users from opening an issue with the underlining repository directly. Lack of knowledge is also why they come to the documentation in the first play.

I think you're confusing "lack of knowledge about a given crate" with "lack of knowledge of how repositories work". And also, if someone doesn't have time to look how to report back to the original repository, I'm not sure if they'll be able to provide a useful feedback to the crate's owner(s)...

> The UI of the documentation presentation needs to be improved. 

Are talking about [docs.rs crate page](https://docs.rs/crate/sysinfo/0.29.0) or [rustdoc page](https://docs.rs/sysinfo/0.29.0/sysinfo/)? In any case, if you have suggestions, please open an issue either here (if docs.rs issue) or on https://github.com/rust-lang/rust (if rustdoc issue) and we'll happily discuss about them.

> The search feature is also problematic as it fails to search examples which often include more conventional phrases for things as oppose to the unique or jargon used by APIs.

I suppose you didn't read the documentation (which leads to an interesting question: how could we make it easier to find)? Rustdoc search only look for API content (functions, struct, etc), not documentation content.

**Comment by Manishearth** [comment]
I am very very wary of adding features like voting, they are far too prone to rather complex social pressures.

People are able to link to their repository sources for feedback and that works pretty well . I do not think the Rust Project should take charge of facilitating feedback between users and crate authors; it requires very large amount of persistent work that we must commit to

**Comment by gdennie** [comment]
[GuillaumeGomez](https://github.com/GuillaumeGomez), I only belatedly became aware that `rustdoc` generates `docs.rs` content. Granted, I may have read it and forgot it earlier.

A Significant value can be derived from improvements in `docs.rs` considering the hundreds of thousands of people it serves on a monthly basis. Cutting their effort down by one minute means hundreds of thousands of minutes gain and thousands of hours freed to the community. It will also help new users tremendously over time as documentation improvements with assistance from those who use it gain their user perspective on treatment.

**Comment by jsha** [comment]
@gdennie welcome, and thanks for wanting to improve the state of documentation!

I agree with @Manishearth and @syphar. Voting on docs is socially complex. As a crate author I would be demotivated rather than encouraged by seeing that twenty people thought my docs were bad. It's also not very actionable - how do I know what problems people are having with them?

On the other hand, if someone takes the time to write a thoughtful comment describing what they're working on, what their experience level is, and what they found confusing or missing in the docs - that's extremely motivating! I'd be excited to write docs with a specific person in mind. It's always helpful to write with an audience in mind.

A "[fork me on GitHub](https://github.blog/2008-12-19-github-ribbons/)" style ribbon could lower barriers to small contributions, but I think that does not do much to improve the quality of documentation overall. Small drive-by edits (like typos) are great, but they are not as useful as thoroughly explaining the purpose of each type, how it interacts with other types, and what some common usage examples are. Also there is no need for a rustdoc or docs.rs feature to implement such a ribbon - doc authors can do it themselves using the full HTML support in rustdoc.

Writing docs is hard work. It's a different skill from writing code. If the people writing docs are not the authors of the code, it requires trust and rapport between them and the authors. Perhaps the most powerful thing that could be done with regards to improving crate documentation would be to establish an organized volunteer group that can offer crate authors a service: a prolonged engagement (e.g. 20 hours per crate) to expand and refine upon their docs. Is that something you'd be interested in trying, @gdennie?

**Comment by gdennie** [comment]
Sure. Sounds like fun. How do we begin, @jsha?

**Comment by Manishearth** [comment]
I would recommend asking in community spaces like Reddit, users.rust-lang.org, perhaps the rust community discord, and seeing if there is interest.

I also recommend we close this issue, I don't think there's further action from the team here at the moment.
