### ISSUE TITLE
Support workspace.metadata

### ISSUE THREAD

**Issue by boozook** [rust-lang/docs.rs#2226]
Is it possible to support `[workspace.metadata.docs.rs]` table? It could be awesome ❤️‍🔥

**Comment by Nemo157** [comment]
The `workspace` table is stripped by cargo when building the package, and it would only be available in the root manifest anyway. I think the best approach would be some way to tell cargo to copy the metadata down into the individual packages, similar to how you can inherit other metadata from the workspace. That was skipped in the [initial RFC](https://github.com/rust-lang/rfcs/blob/master/text/2906-cargo-workspace-deduplicate.md) because it's more complicated than the other fields

> For now the `metadata` key is explicitly left out (due to complications around merging table values), but it can always be added in the future if necessary.

I'd suggest opening a cargo issue about it, it seems a small enough extension to the feature that it might not need an RFC, if someone can come up with a good design.

**Comment by syphar** [comment]
Closing this issue here, since it's a needed cargo change.
