### ISSUE TITLE
Rebuild request for `icu_*` crates

### ISSUE THREAD

**Issue by robertbastian** [rust-lang/docs.rs#2237]
We have fixed a documentation bug in `icu_provider` (1.3.1), which impacts the docs for the following crates (1.3.0):
* `icu`
* `icu_collator`
* `icu_decimal`
* `icu_list`
* `icu_normalizer`
* `icu_plurals`
* `icu_properties`
* `icu_segmenter`
* `icu_timezone`
* `icu_compactdecimal`
* `icu_displaynames`
* `icu_relativetime`
* `icu_transliterate`

Could we please get a rebuild for these?

**Comment by Nemo157** [comment]
Unfortunately a few of those contain a `Cargo.lock`, so we would rebuild with the same version of their dependencies (`icu-1.3.0 icu_decimal-1.3.0 icu_list-1.3.0 icu_plurals-1.3.0`). I can requeue the others tomorrow.

**Comment by robertbastian** [comment]
Huh that's odd, they're all published the same way from the same repo.

**Comment by Nemo157** [comment]
Cargo includes the `Cargo.lock` if the package contains any binary crates, which also counts `examples/`, those four crates are the only ones which have examples from the set. (I'm not sure if there's any way to override cargo's auto determination of this).

**Comment by Nemo157** [comment]
This sort of situation does make me wonder if we should reverse how we do this, instead of building with the `Cargo.lock` initially then removing it if it fails, maybe we should try to build with latest dependencies first, then try applying the `Cargo.lock` if that fails.

**Comment by syphar** [comment]
> This sort of situation does make me wonder if we should reverse how we do this, instead of building with the `Cargo.lock` initially then removing it if it fails, maybe we should try to build with latest dependencies first, then try applying the `Cargo.lock` if that fails.

Perhaps I'm missing something, but wouldn't this kind of defy the purpose of a lockfile, when done generally?

**Comment by syphar** [comment]
Builds are queued

**Comment by robertbastian** [comment]
Lock files in library crates don't do anything, do they? So I if I pull in crate `foo` and run `cargo doc` locally, it will resolve to latest deps. It's a bit weird that the docs.rs version of `foo` uses deps from a lock file iff the crate has examples.

**Comment by Nemo157** [comment]
> Perhaps I'm missing something, but wouldn't this kind of defy the purpose of a lockfile, when done generally?

The main reason for docs.rs to use the lockfile is that we were seeing too many crates which failed to build with updated versions of their dependencies because of accidental semver breakage. It's unlikely that an updated dependency will allow the crate to build but somehow break the docs, so by re-attempting the build with the lockfile if it fails we'll still avoid the issue of semver breakage leading to no docs.

> Lock files in library crates don't do anything, do they?

Lock files in _dependencies_ don't do anything, but docs.rs doesn't build crates as dependencies, it downloads and extracts them and builds them as the top-level crate.

**Comment by robertbastian** [comment]
> Lock files in dependencies don't do anything

Yes, this is what I meant. Presumably users will look at crates on docs.rs in order to use them as dependencies, so the rendering should be as close as possible to that. Of course this assumes an ideal world without accidental semver breakages. That said, a failing docs.rs build is a great signal that your crate does not build without a lock file. Not getting this signal because you have examples in your crate is odd.

**Comment by Nemo157** [comment]
> That said, a failing docs.rs build is a great signal that your crate does not build without a lock file.

It's more important to have the docs available, since for users with an existing lock file they can continue using the crate just fine, and for other users they may be able to manually specify dependency versions to get a working build.

I do have some thoughts around surfacing warnings from our builds to crate owners, if we swap the order of these attempts then showing a warning when we had to use the lockfile would likely be a good candidate to add to those.
