### ISSUE TITLE
Increase memory limit for kube-custom-resources-rs

### ISSUE THREAD

**Issue by sebhoss** [rust-lang/docs.rs#2300]
### Crate name

kube-custom-resources-rs

### Build failure link

https://docs.rs/crate/kube-custom-resources-rs/2023.11.5/builds/960062

### Requested RAM limit

32 GB

### Why your crate needs the resource increases

The crate is quite big and uses lots of [kube-rs](https://kube.rs/) macros on all of its structs. Generating the docs locally takes around 30 GB on my machine with `--jobs 1`.

If increasing the memory limit is not possible, is there some way for me to provide/upload the docs manually?

**Comment by syphar** [comment]
while we can and do increase the memory limit on request, due to the current build-server setup our current max is around 12 GB per build. We _are_ working on this but progress is slow. 
Building yourself and uploading comes with its own issues around security, see #93. 

From what I remember we set a CPU limit of **6 cores** for the docker container, so `--jobs 6` should be more near to the actual build. 

So in the short team I'm happy to increase your limit to 12 GB, if you can make that work.

**Comment by syphar** [comment]
> however I completely get that the requested amount of memory is super high

btw, depending on how many features a user of the library would use the memory usage this high would also be an issue for many developer or CI systems.

**Comment by sebhoss** [comment]
yeah I'm painfully aware :smiling_face_with_tear: however I'm expecting that only a small number of features will be used in downstream projects. I just need to enable all features to verify that all of them work and the entire documentation is generated. My current work around for documentation is to generate it myself with some custom tooling. It certainly isn't perfect but works well on very old hardware..

So thanks again for the fast response & helpful comments!
