### ISSUE TITLE
My crate `prometheus_push` failed to build

### ISSUE THREAD

**Issue by maoertel** [rust-lang/docs.rs#2335]
### Crate name

prometheus_push

### Build failure link

https://docs.rs/crate/prometheus_push/0.4.0/builds

### Additional details

Tried to understand if it is something on my side that caused that but was not able to identify a problem.

Can you please take a look?

Thanks in advance 

Best
Mathias

**Comment by maoertel** [comment]
Ok, found the error but am unsure if this is something that is forbidden:

```
[INFO] [stderr] warning: Target filter specified, but no targets matched. This is a no-op
[INFO] [stderr]  Documenting prometheus_push v0.4.0 (/opt/rustwide/workdir)
[INFO] [stderr] error: Feature 'with_reqwest' and 'with_reqwest_blocking' are mutually exclusive and cannot be enabled together
[INFO] [stderr]    --> src/lib.rs:112:1
[INFO] [stderr]     |
[INFO] [stderr] 112 | compile_error!("Feature 'with_reqwest' and 'with_reqwest_blocking' are mutually exclusive and cannot be enabled together");
[INFO] [stderr]     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr] 
[INFO] [stderr] error: could not document `prometheus_push`
```

Do I have to express mutual exclusive feature somehow different? Or are mutual exclusive features not allowed at all?

**Comment by Nemo157** [comment]
The problem is you are activating both when building on docs.rs

```toml
[package.metadata.docs.rs]
features = ["blocking", "with_reqwest", "with_reqwest_blocking"]
```

You either need to choose just one to activate, or restructure your crate so that both can be active. (Note that because of [how cargo works](https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-unification) having mutually exclusive features is not a great idea, that can cause the same issue when there's multiple dependencies attempting to independently activate each feature individually).

**Comment by maoertel** [comment]
Hey Nemo, got it in the end and disabled two features. Will work on making them all compatible and publish again.

Thanks for your help. :v:
