### ISSUE TITLE
Feature request: Stop the mouse from highlighting search results unless it moves

### ISSUE THREAD

**Issue by jmaargh** [rust-lang/docs.rs#237]
One of the many things I love about docs.rs is that I can use it almost seamlessly without having to reach for my mouse. I would, however, like to request one tiny fix that would improve my workflow greatly.

Right now, I hit [S] to focus the search box, start typing my query, and then use arrows and [Return] to navigate to my result. Unfortunately, my mouse cursor is normally sitting somewhere fairly random in the middle of the window at this point, and as soon as the results show up, the one under the mouse pointer is highlighted. This makes navigating to my desired result annoyingly non-deterministic with the keyboard.

If the mouse cursor could avoid dictating the highlighted result until the mouse moves, then this wouldn't be a problem. I can't imagine it would adversely affect anybody else's use of the website either.

Thanks for the great work.

**Comment by jyn514** [comment]
@jmaargh I think this has since been fixed, I did a search on https://docs.rs/tokio/1.5.0/tokio/?search=tcp and the cursor didn't seem to affect the arrow keys. Feel free to re-open if you're still hitting this issue.

Note that this isn't anything to do with docs.rs, I'd expect the same thing to happen on doc.rust-lang.org.
