### ISSUE TITLE
[Failed]: catgirl-engine crate failed to build

### ISSUE THREAD

**Issue by lexi-the-cute** [rust-lang/docs.rs#2417]
### Crate name

catgirl-engine

### Build failure link

https://docs.rs/crate/catgirl-engine/0.5.0/builds/1124181

### Additional details

winit is the one that contains wayland stuff
```[tasklist]
### Tasks
```

**Comment by syphar** [comment]
It look like this is a bug with `wayland-client`, which doesn't compile on recent nightlies any more: https://github.com/Smithay/wayland-rs/issues/698 

I'm happy to trigger a rebuild when `wayland-client` is fixed. 

If it takes too much time we have the option to _freeze_ the nightly version docs.rs uses, but I think we should wait a bit first to see if the actual issue is fixed quickly enough.

**Comment by syphar** [comment]
The nightly bug was fixed, and a rebuild I triggered succeeded.
