### ISSUE TITLE
[Default Theme Issue]: Ayu

### ISSUE THREAD

**Issue by lexi-the-cute** [rust-lang/docs.rs#2462]
When trying to set the default theme to Ayu, it defaults to the light theme on docs.rs even though it works for local builds. Also, I have to pick the system theme option so the radio button for Ayu becomes available to select

https://docs.rs/crate/catgirl-engine/latest

**Comment by Nemo157** [comment]
The default theme only works on first page load, once any other docs have been loaded and stored their preference into local storage it will not be used. (It does also appear to be buggy, if you clear local storage then load that page no theme at all is used, but given that's a situation that essentially never happens I don't see any reason to fix it).

**Comment by lexi-the-cute** [comment]
I was hoping to make sure the correct theme was chosen for people loading it for the first time. It's kind of the reason why I set the default theme. To make it look nicer and not completely blind people on the first load (I absolutely hate light themes cause of the problems it causes me)

**Comment by syphar** [comment]
> The default theme only works on first page load, once any other docs have been loaded and stored their preference into local storage it will not be used. (It does also appear to be buggy, if you clear local storage then load that page no theme at all is used, but given that's a situation that essentially never happens I don't see any reason to fix it).

So the setting is a user setting and will be used for all of docs.rs then? Or do we have some potential optimization here?

**Comment by lexi-the-cute** [comment]
> > The default theme only works on first page load, once any other docs have been loaded and stored their preference into local storage it will not be used. (It does also appear to be buggy, if you clear local storage then load that page no theme at all is used, but given that's a situation that essentially never happens I don't see any reason to fix it).
> 
> So the setting is a user setting and will be used for all of docs.rs then? Or do we have some potential optimization here?

From my understanding, the default theme only applies if the user hasn't set one yet and the user setting applies site-wide

**Comment by Nemo157** [comment]
The default theme only applies if the user has never visited a page, as soon as a page (that doesn't have a default-theme) is visited the settings are stored into local storage and apply site-wide. Docs.rs' theming (of the topbar and the crates pages) also relies on the settings being stored into local storage, so don't work with a default theme.

I have identified why it's not applying any styling though, rustdoc has migrated to using `<body data-theme="ayu">` at some point instead of loading separate css files, which is what docs.rs has been using too, so because the default theme doesn't get stored into local storage we override that with `data-theme="null"`. I can fix that so at least we don't cause issues with conflicting with rustdoc (e.g. for defaults like this, or more usefully if the default theme-set changes we don't break theming till we update our set too).
