### ISSUE TITLE
error: failed to run custom build command for `ring v0.17.8`

### ISSUE THREAD

**Issue by xmh0511** [rust-lang/docs.rs#2501]
### Crate name

webserver-rs

### Build failure link

https://docs.rs/crate/webserver-rs/0.5.2/builds/1202362/x86_64-apple-darwin.txt

### Additional details

The doc generates failure for Windows and Apple-Darwin platforms.

**Comment by syphar** [comment]
sorry for the delayed response. 
Currently we are using cross compilation to compile all non-default platforms. 

In this case, `ring` can't be compiled like this on non-default platforms, which is probably also why [its docs are only available for one platform](https://docs.rs/ring/latest/ring/). We don't see the failing logs because [storing them was added later](https://github.com/rust-lang/docs.rs/pull/2427). 

#1957 might be a solution, or #93. Until them, many crates choose conditional compilation to make the crate build purely for docs in our build. 


for reference: 
- https://docs.rs/about/builds
