### ISSUE TITLE
liboxen docs failing

### ISSUE THREAD

**Issue by gschoeni** [rust-lang/docs.rs#2515]
### Crate name

liboxen

### Build failure link

https://docs.rs/crate/liboxen/0.15.13/builds/1243240

### Requested RAM limit

8GB

### Requested timeout

30 minutes

### Why your crate needs the resource increases

Not sure why it keeps failing on the duckdb build, it seems like their docs build fine. Maybe there is some other configuration I am missing. Any pointers would be helpful, but I thought I'd try extending the RAM and the timeout.

**Comment by syphar** [comment]
the error says `ReadOnlyFilesystem`, which means it's definitely not related to our memory limit. 

My (wild) guess would be that the `bundled` feature you're setting results in this error, because then the duckdb lib tries to write into a directory it shouldn't. 

The `libduckdb_sys` docs themselves don't set this feature, so the build succeeds there. 

So you could: 
- not set this feature for the doc-build, or 
- provide a fix to the duckdb library that it only writes to cargo `OUT_DIR` (which is writable)(

**Comment by gschoeni** [comment]
Thanks for following up! Let me try disabling the feature for the doc-build

**Comment by syphar** [comment]
I see the build for the last version has succeeded, so I'll close this issue.
