### ISSUE TITLE
Crate succeeds to build, but some pages are unreachable

### ISSUE THREAD

**Issue by Bromeon** [rust-lang/docs.rs#2536]
### Crate name

godot

### Build failure link

https://docs.rs/crate/godot/0.1.1/builds

### Additional details

Several modules in the `godot` crate page are unreachable. Some like `builtin` work, others like `classes` don't.
https://docs.rs/godot/0.1.1/godot/#modules

The error message is: _The requested resource does not exist_

In case this is a misconfiguration on my side, could you help me point that out? 
See also downstream issue https://github.com/godot-rust/gdext/issues/779.

Thanks a lot in advance! :slightly_smiling_face:

**Comment by syphar** [comment]
This odd, but I have a hunch what the reason could be. 

I'm currently on the way back from rustfest zürich, with wonky internet connection, will look into it later today

**Comment by syphar** [comment]
Still odd, I checked the two typical issues / solutions for these kind of errors, both didn't help. 

I need to dig deeper and see if I can reproduce this locally to debug

**Comment by StatisMike** [comment]
At least currently, all pages seem to be showing up on when choosing every platform besides `x86_62-unknown-linux-gnu` (which is default)

**Comment by syphar** [comment]
note to myself,  things I just checked: 
- normal `cargo doc` locally looks good 
- the archive of the built docs ( https://docs.rs/crate/godot/latest/download ) looks complete for all targets 

next step: 
- run the build locally, so I can see if the issue is in the webserver, or the archive index file

**Comment by syphar** [comment]
now it gets tricky: local build succeeds, and all pages I tested worked. 

in the logs on the server I saw an odd "missing bz2 header", though I couldn't directly link it to this crate. 

Next test I'll do is to download the archive index & archive from S3, and test locally with these. Also I'll probably have to extend logging in the respective handler.

**Comment by syphar** [comment]
I found the issue and deployed a fix. 

A rebuild is queued after which it should be fine for this crate release. 

I'll leave this issue open since I also have to queue rebuilds (or just fix the archive indexes) for all affected releases since I deployed https://github.com/rust-lang/docs.rs/pull/2520, so ~june 23nd

**Comment by syphar** [comment]
I found another issue on the zip library for this https://github.com/zip-rs/zip2/issues/189 

let's see how it's fixed

**Comment by Bromeon** [comment]
Thank you so much! ❤️
