### ISSUE TITLE
romio: Documentation failed to build on docs.rs

### ISSUE THREAD

**Issue by kpp** [rust-lang/docs.rs#267]
https://docs.rs/releases/search?query=romio

> The requested resource does not exist

Crate [romio](https://crates.io/crates/romio/) requires nightly, is it the issue for missing docs?

Fixes https://github.com/withoutboats/romio/issues/44

**Comment by QuietMisdreavus** [comment]
Attempting to build it by hand with the latest nightly rustc yields the following log:

```
2018/11/30 20:42:42 [DEBUG] cratesfyi::docbuilder: Loading cache
2018/11/30 20:42:42 [DEBUG] cratesfyi::docbuilder: Loading database cache
2018/11/30 20:42:43 [INFO] cratesfyi::docbuilder::chroot_builder: Building package romio-0.3.0-alpha.1
2018/11/30 20:42:43 [DEBUG] cratesfyi::utils::build_doc: Getting package with cargo
    Updating crates.io index
thread 'main' panicked at 'Building documentation failed: ErrorMessage { msg: "feature `rename-dependency` is required\n\nconsider adding `cargo-features = [\"rename-dependency\"]` to the manifest" }

failed to parse manifest at `/srv/cratesfyi/.cargo/registry/src/github.com-1ecc6299db9ec823/romio-0.3.0-alpha.1/Cargo.toml`

unable to get packages from source', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This tells me it's not a problem of needing a new *rustc*, but a new *cargo*. Updating cargo on docs.rs requires updating the site itself, since it uses cargo as a library. I'll work on this once the Rustdoc Team gets permission on the recently-moved repo and our CI gets updated.

**Comment by kpp** [comment]
@onur Would you please trigger the build to see whether the fix worked or not?

**Comment by onur** [comment]
@kpp its been built now: https://docs.rs/romio

**Comment by kpp** [comment]
Thanks!
