### ISSUE TITLE
[src] Line numbers are broken

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/docs.rs#280]
`[src]` is broken for a couple of months, at least for me.
https://docs.rs/ash/0.26.2/src/ash/device.rs.html#1700-1704

![](https://i.imgur.com/hHdUpqv.png)

Can anyone reproduce this?

**Comment by QuietMisdreavus** [comment]
Duplicate of https://github.com/rust-lang/docs.rs/issues/264, but it won't be fixed until we update the nightly on the server. (I need to wait to do this until https://github.com/rust-lang/docs.rs/pull/281 is merged, since the new nightly has a new static file that we'll want to cache.)

Certain versions of rustdoc generated docs that did this. To fix it, we'll need to generate the docs that were built with those versions.

**Comment by MaikKlein** [comment]
It seems as if it has already been fixed even without #281
