### ISSUE TITLE
badge links unnecessarily redirect to an HTTP endpoint

### ISSUE THREAD

**Issue by reuvenpo** [rust-lang/docs.rs#363]
Fetching badge links (such as e.g. https://docs.rs/py-comp/badge.svg) requires going through two redirects:

```
$ wget https://docs.rs/py-comp/badge.svg
--2019-06-03 23:14:30--  https://docs.rs/py-comp/badge.svg
Resolving docs.rs (docs.rs)... 52.222.167.82, 52.222.167.16, 52.222.167.22, ...
Connecting to docs.rs (docs.rs)|52.222.167.82|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://docs.rs/py-comp/badge.svg?version=0.1.3 [following]
--2019-06-03 23:14:36--  http://docs.rs/py-comp/badge.svg?version=0.1.3
Connecting to docs.rs (docs.rs)|52.222.167.82|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://docs.rs/py-comp/badge.svg?version=0.1.3 [following]
--2019-06-03 23:14:37--  https://docs.rs/py-comp/badge.svg?version=0.1.3
Connecting to docs.rs (docs.rs)|52.222.167.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 884 [image/svg+xml]
Saving to: ‘badge.svg’
```

In trying to fetch the badge, three HTTP calls are made:

1. https://docs.rs/py-comp/badge.svg --> 302 Moved Temporarily
2. http://docs.rs/py-comp/badge.svg?version=0.1.3 --> 301 Moved Permanently
3. https://docs.rs/py-comp/badge.svg?version=0.1.3 --> 200 OK

Besides the fact that this is unnecessary (because the first endpoint can just return the badge for the latest version by default), it messes with downstream uses.
Specifically, VSCode don't follow HTTP links when trying to fetch badges for display in markdown previews when "strict" security is enabled. This means that it stops following links at (2) and refuses to display the badge.

See https://github.com/microsoft/vscode/issues/73531 for reference.

**Comment by HeroicKatora** [comment]
For that specific request, the redirection answer is built using `req.url.scheme()`: https://github.com/rust-lang/docs.rs/blob/70e5a44a423be65fd1e45505051f7e277b65a1fc/src/web/rustdoc.rs#L300

But this seems to be a general issue with redirects, maybe caused by some tls termination proxy in front of the actual `docs.rs` instance, you can observe the same behaviour if you monitor the redictions for the crate version resolution as well, e.g. `https://docs.rs/image/`:

```
$ wget https://docs.rs/image
--2019-06-04 11:02:28--  https://docs.rs/image
Resolving docs.rs (docs.rs)... 99.84.92.65, 99.84.92.25, 99.84.92.107, ...
Connecting to docs.rs (docs.rs)|99.84.92.65|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://docs.rs/image/0.21.1/image/ [following]
--2019-06-04 11:02:29--  http://docs.rs/image/0.21.1/image/
Connecting to docs.rs (docs.rs)|99.84.92.65|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://docs.rs/image/0.21.1/image/ [following]
--2019-06-04 11:02:29--  https://docs.rs/image/0.21.1/image/
Connecting to docs.rs (docs.rs)|99.84.92.65|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44834 (44K) [text/html]
```

Also affected: [Feeling lucky](https://github.com/rust-lang/docs.rs/blob/09283ef5f0189195c0249cd46a1fc73f202cec9d/src/web/releases.rs#L448), [crate details](https://github.com/rust-lang/docs.rs/blob/62680b0ecafc677de49db1898afb7b4f352c1595/src/web/crate_details.rs#L243). This is also a security concern in so far as those plaintext redirections can be intercepted an arbitrarily modified and also leak the requested package url on the network.

**Comment by HeroicKatora** [comment]
Potential fix would be to set and parse the [`Forwarded`](https://tools.ietf.org/html/rfc7239#section-1) header in whatever terminates the https connection and use the encoded original protocol instead of the scheme if available.

**Comment by pietroalbini** [comment]
@HeroicKatora thanks so much for investigating this! I'll handle the server configuration.
