### ISSUE TITLE
neon crate did not build

### ISSUE THREAD

**Issue by kjvalencik** [rust-lang/docs.rs#446]
**Crate name:** [neon@0.3.3-napi](https://crates.io/crates/neon/0.3.3-napi)
**Build failure link:** N/A

**Additional details:**

* The build initially entered the build queue
* After moving from the build queue it did **not** show in recent
* `0.3.3-napi` was not added to docs.rs

A potentially contributing factor is that `0.3.3-napi` was released _after_ `0.3.3` which is not typical for pre-releases.

**Comment by jyn514** [comment]
Possibly related to https://github.com/rust-lang/docs.rs/issues/395.

**Comment by jyn514** [comment]
@kjvalencik I see that the build for neon 0.4.0 succeeded, so I'm going to close this. Unfortunately we only keep server logs for about a week so there's no way now to tell the root cause of the failure. The reason you didn't see it added to recent or failed builds is mostly likely https://github.com/rust-lang/docs.rs/issues/797.
