### ISSUE TITLE
libtls crate needs LibreSSL

### ISSUE THREAD

**Issue by reyk** [rust-lang/docs.rs#462]
**Crate name:**
libtls-sys

**Build failure link:** 
https://docs.rs/crate/libtls-sys/1.0.0-alpha1/builds/195544
https://docs.rs/crate/libtls-sys/1.0.0-alpha2/builds/195554
https://docs.rs/crate/libtls-sys/1.0.0-alpha3/builds/195557
https://docs.rs/crate/libtls-sys/1.0.0-alpha4/builds/195560

**Additional details:**
libtls-sys links against [LibreSSL](https://www.libressl.org/) 3.0.2 which includes the `libtls` library. This library only exists in LibreSSL, not OpenSSL, but is not packaged by all Linux distributions. The crate build code tries to download and to compile LibreSSL if it cannot be found. The build passes on Ubuntu in Travis CI and on OpenBSD, but not in the docs.rs containers.

**Comment by jyn514** [comment]
cc @pietroalbini , I think this would require a change to Rustwide's `crate-build-environment` image. Not sure what the policy is for that.

**Comment by pietroalbini** [comment]
Seems like libressl is not packaged for Ubuntu 18.04? So far the policy has been only to install dependencies from the Ubuntu archives.

> The crate build code tries to download and to compile LibreSSL if it cannot be found.

Network access is blocked from the build environment. A thing other crates (like `rusqlite`) are doing is to vendor the C source code in the crate and provide a feature flag to compile and use the bundled version. Maybe that could be tried here too?

**Comment by reyk** [comment]
Thanks for the info, I now understand the constraints better. I don't like the idea of bundling the ~3.5M of LibreSSL source code but maybe it works by using a branch that is just used for publishing it on crates.io / docs.rs - it would still bloat the git objects and put the burden on me to sync the releases.

I think the dependency on Ubuntu's packages is somehow contradicting Rust's portability claims. Maybe it is `cargo publish` that should allow to upload supplementary tarballs that aren't part of the git repo.

**Comment by pietroalbini** [comment]
> Thanks for the info, I now understand the constraints better. I don't like the idea of bundling the ~3.5M of LibreSSL source code but maybe it works by using a branch that is just used for publishing it on crates.io / docs.rs - it would still bloat the git objects and put the burden on me to sync the releases.

What you could do there is create a separate, `libressl-c-code` (or whatever name you like) crate that basically contains the LibreSSL source code, and only pull it as a dependency with a feature flag. That way most users don't download the extra stuff, but people who need to build without internet access can do that.

> I think the dependency on Ubuntu's packages is somehow contradicting Rust's portability claims.

To be clear, **docs.rs** requires the dependency to be packaged in the Ubuntu repository, and it requires that just because Ubuntu happens to be the distro used in our build environment. You can surely depend on whatever you need outside of docs.rs :)

> Maybe it is cargo publish that should allow to upload supplementary tarballs that aren't part of the git repo.

Well, you can already publish whatever you want to crates.io, even if you don't use git. Cargo by default sets up git and warns you if you try to upload uncommitted stuff, but that's just to help developers to do what we think is good practice. That's just a default behavior, and it can be overridden.
