### ISSUE TITLE
docs.rs should ignore rust-toolchain

### ISSUE THREAD

**Issue by eldesh** [rust-lang/docs.rs#555]
dockworker which is a docker client library.
Building this crate failed on docs.rs :(

**Crate name:**
dockworker

**Build failure link:**
https://docs.rs/crate/dockworker/0.0.15

**Additional details:**
On my local machine (Ubuntu 18.04 LTS), building succeeds.

**Comment by pietroalbini** [comment]
Seems like the `rust-toolchain` in the source code is present, asking rustup to install 1.32.0 instead of the nightly used by docs.rs. This is not your crate's fault, docs.rs should remove that file.

Writing mentoring instructions if anyone wants to fix this issue:

---

To fix this issue, a new [prepare step](https://github.com/rust-lang/rustwide/blob/b6a88935d521637a9d182c766aa7bef04a1a5815/src/prepare.rs#L41) to remove that file from the source directory should be added to [rustwide](https://github.com/rust-lang/rustwide), before the manifest is read. In addition to that, a rustwide [buildtest](https://github.com/rust-lang/rustwide/tree/master/tests/buildtest) needs to be added: create a dummy crate in rustwide's [`tests/buildtest/crates`](https://github.com/rust-lang/rustwide/tree/master/tests/buildtest/crates) with a `rust-toolchain` file in it pointing to a really old version (like 1.0.0), and [create a test](https://github.com/rust-lang/rustwide/blob/master/tests/buildtest/mod.rs) that calls `rustc --version` and ensures it's not actually 1.0.0.

Once rustwide is updated and a new version is released you should open a PR to docs.rs bumping rustwide.

If anyone wants to work on this issue please say so in the comments, so we don't have multiple people working on the same issue. If you need help implementing it feel free to comment here or [hop on Discord (channel `#docs-rs`)](https://discord.gg/rust-lang). Check out the [contributing guidelines](https://github.com/rust-lang/docs.rs#development) as well!

**Comment by Freax13** [comment]
I have trouble implementing the test for this.

I tried
```rust
#[test]
fn test_toolchain_override() {
    runner::run("toolchain-override", |run| {
        run.build(SandboxBuilder::new().enable_networking(false), |build| {
            let storage = rustwide::logging::LogStorage::new(LevelFilter::Info);
            rustwide::logging::capture(&storage, || -> Result<_, Error> {
                build.cargo().args(&["rustc", "--", "--version"]).run()?;
                Ok(())
            })?;

            // some check
            Ok(())
        })?;
        Ok(())
    });
}
```
but this doesn't work because it ignores the `rust-toolchain` file anyways. I'm not sure what causes rustup to install the new toolchain with docs.rs and not with the test

**Comment by jyn514** [comment]
It seems the behavior of docs.rs has changed since the issue was opened.
```
$ RUST_LOG=info cargo run -q build crate -l ../toolchain-test/
...
2020/05/06 09:21:35 [INFO] rustwide::cmd: running `"/home/joshua/src/rust/docs.rs/.rustwide/cargo-home/bin/cargo" "+nightly" "metadata" "--format-version" "1"`
2020/05/06 09:21:35 [INFO] rustwide::cmd: running `"docker" "create" "-v" "/home/joshua/src/rust/docs.rs/.rustwide/builds/toolchain-test-0.1.0/target:/opt/rustwide/target:rw,Z" "-v" "/home/joshua/src/rust/docs.rs/.rustwide/builds/toolchain-test-0.1.0/source:/opt/rustwide/workdir:ro,Z" "-v" "/home/joshua/src/rust/docs.rs/.rustwide/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/home/joshua/src/rust/docs.rs/.rustwide/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "MAP_USER_ID=1000" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "RUSTFLAGS=" "-e" "RUSTDOCFLAGS=-Z unstable-options --resource-suffix -20200505-1.45.0-nightly-f8d394e51 --static-root-path / --cap-lints warn" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--network" "none" "rustops/crates-build-env" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "doc" "--lib" "--no-deps" "--target" "x86_64-apple-darwin"`
2020/05/06 09:21:35 [INFO] rustwide::cmd: [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
2020/05/06 09:21:35 [INFO] rustwide::cmd: [stdout] 707d87ecf6f8af1962a614f48d95fb6e771de0c22955053de8fbd605a618795f
2020/05/06 09:21:35 [INFO] rustwide::cmd: running `"docker" "start" "-a" "707d87ecf6f8af1962a614f48d95fb6e771de0c22955053de8fbd605a618795f"`
2020/05/06 09:21:36 [INFO] rustwide::cmd: [stderr] sudo: setrlimit(RLIMIT_CORE): Operation not permitted
2020/05/06 09:21:36 [INFO] rustwide::cmd: [stderr]  Documenting toolchain-test v0.1.0 (/opt/rustwide/workdir)
2020/05/06 09:21:37 [INFO] rustwide::cmd: [stderr]     Finished dev [unoptimized + debuginfo] target(s) in 0.87s
2020/05/06 09:21:37 [INFO] rustwide::cmd: running `"docker" "inspect" "707d87ecf6f8af1962a614f48d95fb6e771de0c22955053de8fbd605a618795f"`
2020/05/06 09:21:37 [INFO] rustwide::cmd: running `"docker" "rm" "-f" "707d87ecf6f8af1962a614f48d95fb6e771de0c22955053de8fbd605a618795f"`
2020/05/06 09:21:37 [INFO] rustwide::cmd: [stdout] 707d87ecf6f8af1962a614f48d95fb6e771de0c22955053de8fbd605a618795f
2020/05/06 09:21:37 [INFO] cratesfyi::docbuilder::rustwide_builder: .rustwide/builds/toolchain-test-0.1.0/target/x86_64-apple-darwin/doc /tmp/docsrs-docs.tXHW1a5ZzcAC/x86_64-apple-darwin
thread 'main' panicked at 'Building documentation failed: ErrorMessage { msg: "Not a JSON object" }', src/bin/cratesfyi.rs:199:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
We'll have to figure out where this new panic is coming from, it only happens in crates with this toolchain error (I checked with `target_lexicon 0.10.0` and a custom test that only had `default-run = "toolchain-test"` in Cargo.toml and `1.34.0` in `rust-toolchain`).

**Comment by Freax13** [comment]
running `RUST_BACKTRACE=1 RUST_LOG=info cargo run build crate target-lexicon 0.10.0` works for me

**Comment by jyn514** [comment]
Yes I was a little unclear sorry - `target-lexicon` builds successfully but the `toolchain-test` crate did not.

**Comment by Freax13** [comment]
the error is coming from https://github.com/rust-lang/docs.rs/blob/103cacc61f544df48e20ff8a00830f7a40139b06/src/db/add_package.rs#L303

**Comment by Freax13** [comment]
okay, so for some reason `get_release_time_yanked_downloads` is called which tries to download the info about `toolchain-test` from crates.io (https://crates.io/api/v1/crates/toolchain-test/versions).

I'm not sure if this is related to removing the `rust-toolchain` file
