### ISSUE TITLE
Better documentation for how to build crates locally

### ISSUE THREAD

**Issue by jackgerrits** [rust-lang/docs.rs#574]
Is it possible to locally test a documentation build for a crate? If so, is there any documentation about doing this? If there is a docker container or something I'd be happy to help improve to docs with this. I am asking as I had an issue where my -sys crate was having trouble building on docs.rs and I had to rerelease several times to fix all of the issues.

**Comment by jyn514** [comment]
Yes, this is documented [in the README](https://github.com/rust-lang/docs.rs/blob/master/README.md#build-subcommand). It might be nice to also add it to the `/about` page.

**Comment by jyn514** [comment]
Mentoring instructions:

- modify [`templates/about.hbs`](https://github.com/rust-lang/docs.rs/blob/master/templates/about.hbs#L54) to point to the README
- optionally, make it more explicit in the README that `--local` works.

Partially I think this is hard to find because the README is so big, so it might be nice to split that up into README for users and CONTRIBUTING for contributors.
