### ISSUE TITLE
Limited http requests with permissions to build a crate

### ISSUE THREAD

**Issue by yaa110** [rust-lang/docs.rs#605]
Some crates need to download a source code to generate ffi bindings (issue #602). It would be helpful to add a `permissions` section to Cargo.toml to allow crates access declared urls in that section.

**Comment by jyn514** [comment]
This is the same as unlimited network access, since you could just put any URL in the `permissions` section. We _could_ override this on a case by case basis, but I am not comfortable doing that for security reasons. Please find an alternative way to build your crate that does not require internet access.

**Comment by jyn514** [comment]
Note that this affects me too, I develop https://docs.rs/crate/yottadb/0.3.0 which requires internet access to download the C package it depends on. My solution was to host the documentation on GitLab Pages instead and link there from the crate README, maybe that will work for you?
