### ISSUE TITLE
Broken rust icon link

### ISSUE THREAD

**Issue by Zexbe** [rust-lang/docs.rs#618]
If you go to this link
https://docs.rs/brotli/3.3.0/brotli/index.html
The rust icon has a bad link that goes to
https://docs.rs/-20190128-1.34.0-nightly-d8a0dd7ae/index.html

**Comment by reese** [comment]
Hmm, not sure the source of that, since presumably that's a failure originating in `rustdoc` from nightly at the time of that build, which was over a year ago. Interestingly enough, that's true for all of 3.* versions of `brotli`, and the [2.* versions](https://docs.rs/brotli/2.3.0/brotli/) don't have the icon at all.

That said, I re-built this crate locally and the icon link works as expected, so the fix for this may just be to re-build that crate if that's possible.

**Comment by jyn514** [comment]
Duplicate of #464

**Comment by jyn514** [comment]
Rebuilt brotli 3.3.0 just now so the link is fixed for that version at least.
