### ISSUE TITLE
How to compile documentation for https://docs.rs/crate/rust_icu_sys

### ISSUE THREAD

**Issue by filmil** [rust-lang/docs.rs#655]
**Crate name:** `rust_icu_sys`
**Build failure link:** https://docs.rs/crate/rust_icu_sys/0.1.1/builds/233436

**Additional details:**
Hi folks!  I'd like to ask for some guidance regarding the crate `rust_icu_sys` that I maintain.  docs.rs is not able to compile the crate, since compilation requires some additional libraries and tools, like the Unicode ICU library, as well as clang, bindgen, and others.  

What would be the best way to bring those dependencies in so that documentation could be built on docs.rs?  Thanks!

**Comment by jyn514** [comment]
clang [should already be installed](https://github.com/rust-lang/crates-build-env/blob/master/packages.txt#L12) in the build environment. I'm not sure what Unicode ICU is, but as long as Ubuntu packages it, you can add it to the environment by [making a PR](https://forge.rust-lang.org/docs-rs/add-dependencies.html). Bindgen will be a little harder because it's not packaged. Have you considered using bindgen as a library instead of calling the binary? See https://docs.rs/bindgen/0.53.2/bindgen/ for docs on how to do that.

**Comment by filmil** [comment]
Thanks for the advice. I was looking for recommendations, and this is
exactly what I was looking for.

F

**Comment by filmil** [comment]
I think I made some progress as advised, closing this issue.

If you are curious, feel free to look at: https://github.com/google/rust_icu/issues/41

**Comment by jyn514** [comment]
I'm glad I could help!
