### ISSUE TITLE
Make release updating happen in add_package_to_database

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/docs.rs#798]
Currently we have three separate parts of adding and fully recognizing a new release, [`add_package_to_database`](https://github.com/rust-lang/docs.rs/blob/master/src/db/add_package.rs), [`update_search_index`](https://github.com/rust-lang/docs.rs/blob/master/src/db/mod.rs#L66) and [`update_release_activity`](https://github.com/rust-lang/docs.rs/blob/master/src/utils/release_activity_updater.rs#L6). These should all be able to be combined, which would remove two side services (both updaters run on separate threads) and make publishing releases more responsive for users

**Comment by Nemo157** [comment]
`update_search_index` writes `crates.content` which appears to be unused since https://github.com/rust-lang/docs.rs/pull/721 so it can probably just be dropped and this function deleted.

`update_release_activity` I assume is for the chart on https://docs.rs/releases/activity, those queries look simple enough, and that page is requested rarely enough, that I don't think those calculations need caching, they could just be done when that page is loaded. (Especially if rewritten to be a single query as I think it can be).

**Comment by Kixiron** [comment]
Closed by #804
