### ISSUE TITLE
newton_rootfinder 0.4.0 failed to build

### ISSUE THREAD

**Issue by Nateckert** [rust-lang/docs.rs#811]
**Crate name:** newton_rootfinder
**Build failure link:** https://docs.rs/crate/newton_rootfinder/0.4.0/builds/255472

**Additional details: ** the error seems to be related to the build of a dependencies. This dependencies has its documentation up-to-date on doc.rs.

I tried on my computed with stable Rust and its working fine.
However, the build on doc.rs seems to have been done with : `rustc 1.45.0-nightly (451272115 2020-05-28)`

I tried also on my computer with `rustc 1.45.0-nightly (a74d1862d 2020-05-14)` and `rustc 1.45.0-nightly (56daaf669 2020-06-03)`. The building of the documentation works for both locally.

Thanks in advance !

**Comment by jyn514** [comment]
This happens because `rustc_version_runtime` tries to write to its source directory, which is not allowed; it should instead write to `$CARGO_OUT_DIR`. The fact that the rustc_version_runtime build succeeded is odd, that means that that they're doing something special when built for docs.rs. I recommend filing a bug upstream with that crate.

**Comment by Nemo157** [comment]
`rustc_version_runtime` has just not published a version since that restriction went into place.

**Comment by jyn514** [comment]
I saw that the build succeeded in 0.5.0, so I'm going to close this issue. Feel free to re-open if you're still having trouble!
