### ISSUE TITLE
Tests freeze computer

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/docs.rs#827]
On Windows 10 tests with lots of errors (or sometimes lots of output, it's really hard to tell) freeze my pc, cutting sound, video and in one instance even giving me a full on BSOD. I've got no idea why it happens and why it only happens sometimes, I think it's something to do with panics since they have what's essentially an exponential growth because of mutex poisoning. Another possibility is that it's because we delay all cleanup of resources until the very end of testing, which somehow absolutely trashes things

**Comment by jyn514** [comment]
We should get rid of `PoisonError` anyway, it makes it hard to find the original source of the error.

**Comment by Kixiron** [comment]
I've been wanting to redo the error system some for a while, like making `wrapper` into a macro so that we can preserve the error location while still being able to use `?`

**Comment by Nemo157** [comment]
I would wait for <https://github.com/rust-lang/rust/pull/72445> if it comes soon, macros are a real pain to work with.

**Comment by Kixiron** [comment]
Yes, track caller was my ideal, but I wasn't sure as to the timeline of it getting stabilized

**Comment by jyn514** [comment]
We can use `.backtrace()` right now without changing dependencies, if someone wants to make a PR updating `wrapper()` that would be great.

**Comment by jyn514** [comment]
We could also change to using transactions instead of setting up a temporary table for each new test: https://docs.rs/postgres/0.15.2/postgres/transaction/struct.Transaction.html#method.connection

**Comment by pietroalbini** [comment]
I'm not sure that's a good idea: the current setup makes sure the migrations works, and guarantees a clean environment each time the test is executed. Using a transaction in an already-initialized database could result in stale data being used, and it might be problematic if you hop between branches changing the database schema.

**Comment by Kixiron** [comment]
It would be nice if we only ran migrations once per `cargo test` since they're *really* slow

**Comment by jyn514** [comment]
>  the current setup guarantees a clean environment each time the test is executed

Since this is in test code, we'll notice immediately if it breaks.

> Using a transaction in an already-initialized database could result in stale data being used

This is only an issue if you mix transactions and connections. My idea was to return `transaction.connection()` from `TestDatabase::conn` so that _all_ database queries use the same transaction: https://github.com/rust-lang/docs.rs/blob/b58f2daef60f16aa9102f60a334389a72d250166/src/test/mod.rs#L163

> it might be problematic if you hop between branches changing the database schema

I'm confused what you mean here? My idea was to reinitialize from scratch once (and only once) on each `cargo test`, so it would still be updated if you changed `migrations.rs`.

**Comment by pietroalbini** [comment]
@jyn514 so, if I understood it correctly your idea is that when `cargo test` starts a schema is created and migrated, and then all the tests run in transactions inside the same schema?

**Comment by jyn514** [comment]
Exactly. We could implement that with a once_cell or similar.

**Comment by jyn514** [comment]
Hmm, I think this will need larger changes than I expected - the web server also takes a connection pool, and the state the server sees has to match the state the `FakeDatabase` created. A pool won't work because each connection will be a different transaction.

Maybe we could change `Context::pool` to return a connection directly? But there's a lot of the codebase currently depending that it has a pool and not a single connection.

**Comment by syphar** [comment]
from what I see the needed changes described are already how our test-suite work right now. 

It's still slow and pending some other improvements, but it shoudn't freeze.
