### ISSUE TITLE
yew_styles 5.0 is still not publish in docs.rs and I released almost 2 days ago

### ISSUE THREAD

**Issue by dancespiele** [rust-lang/docs.rs#835]
I released the version 5.0 yew_styles almost 2 days ago and usually the create only get two or three hours to be published in docs.rs. i don't know if there was something wrong but when I published the new version I didn't get any error and now the new version docs doesn't exist, only show the previous versions.

crate: https://crates.io/crates/yew_styles
command to publish: `cargo publish --target wasm32-unknown-unknown --all-features`
github: https://github.com/spielrs/yew_styles/tree/master/crate/yew_styles

**Comment by Nemo157** [comment]
I built on my local docs.rs and it published fine (though the doc build itself failed because of missing features, I suggest you [add metadata to your package](https://docs.rs/about#metadata) to enable all-features, set the default target to `wasm32-unknown-unknown`, and disable other targets; but that should still result in getting a page saying that the build failed).

Looking at the metrics something happened a couple of minutes (2020-06-11T23:39Z) after this was published (2020-06-11T23:37Z), but comparing the index commits and the queue size it looks like it was added to the queue right on time, and I don't see anything that makes it look like there were issues around when it should have been built (~2020-06-12T00:50Z based on [builds](https://docs.rs/crate/lelet/1.2.14/builds/260273) from [either](https://docs.rs/crate/peepmatic-macro/0.2.0/builds/260274) side in the index).

@pietroalbini or @jyn514 can requeue the doc build (and it'd be great to check if there's anything in the logs around those timestamps).

**Comment by dancespiele** [comment]
I can release 0.5.1 with all you suggestions but maybe I should wait until they can check if there is anything in the logs because could be there is someway which I don't need to release again however for the next releases I will follow your recommendations.

**Comment by jyn514** [comment]
These are the logs:
```
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: running `Command { std: "/home/cratesfyi/workspace/cargo-home/bin/cargo" "+nightly" "fetch" "--locked" "--manifest-path" "Cargo.toml", kill_on_drop: false }`
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr] error: failed to download `yew v0.16.2`
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr]
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr] Caused by:
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr]   unable to get packages from source
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr]
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr] Caused by:
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr]   failed to parse manifest at `/home/cratesfyi/workspace/cargo-home/registry/src/github.com-1ecc6299db9ec823/yew-0.16.2/Cargo.toml`
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr]
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr] Caused by:
Jun 12 00:50:07 docsrs cratesfyi[16410]: 2020/06/12 00:50:07 [INFO] rustwide::cmd: [stderr]   readme file with name '../README.md' was not found
```
This looks like the same issue as https://github.com/rust-lang/docs.rs/issues/832, I'll queue a rebuild.

**Comment by Nemo157** [comment]
Oh, 🤦 I looked at the version on the builds from either side to see if it might be related to that, but forgot that the `rustc` version and the nightly date are off-by-one.

**Comment by jyn514** [comment]
The build finished successfully and failed like nemo said: https://docs.rs/crate/yew_styles/0.5.0/

Going to close this since we fixed the bug on our end, let us know if you need help getting it to build.
