### ISSUE TITLE
Get rid of the `ctry!` & `cexpect!` macros

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#860]
Pretty sure we can literally just replace ctry! with ? now given that errors without an explicit status code are treated as 500s (or if we can't, could try and make it so that we can). That would allow changing `cexpect!` usage into `.ok_or_else(|| err_msg(...))?`.

_Originally posted by @Kixiron and @nemo157 in https://github.com/rust-lang/docs.rs/pull/858#issuecomment-650672242_

**Comment by Nemo157** [comment]
Ok, I just attempted this, and it's not trivial at the moment. `IronError` doesn't implement `From` to allow using `?` with it since it smushes together application level HTTP error codes and underlying server errors into the same type. This should be doable after/as part of the transition to `hyper` as long as we don't make the same mistake with the design of our "`Handler`".

**Comment by jyn514** [comment]
An easy way to make this nicer is `impl From<Nope> for IronError` - it will still need `map_err` in a few places, but fewer of them and shorter.

**Comment by syphar** [comment]
both macros are gone after the axum migration was finished.
