### ISSUE TITLE
Switch from html5ever to lol_html

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#876]
See https://github.com/kuchiki-rs/kuchiki/pull/74#issuecomment-653184255 for discussion. In a nutshell, kuchiki is not intended for low-memory usage: it uses lots of Rc and RefCell (one for each node in the tree!) LOL HTML is intended for exactly our use case:

> Low Output Latency streaming HTML rewriter/parser with CSS-selector based API.

This would allow us to step the size of files rendered _way_ up, possibly removing the limit altogether (https://github.com/rust-lang/docs.rs/pull/834).

**Comment by jyn514** [comment]
LOL HTML is also developed by cloudflare so it has seen a lot of real-world usage.

**Comment by Kixiron** [comment]
I think having *a* limit even if it's absurdly high and will "never" be hit is something good, just as a safeguard

**Comment by Kixiron** [comment]
And according to [Cloudflare's blog post](https://blog.cloudflare.com/html-parsing-2/#byte-slice-processing-optimisations) LOL Html is vastly faster than html5ever and scales *much* better. I believe our performance will be somewhere in the ballpark of the tag scanner, but potentially even better than "normal" parsing since we grab two portions of the html and LOL doesn't parse innards if you specify a tag, while html5ever parses everything unconditionally

![](https://blog-cloudflare-com-assets.storage.googleapis.com/2019/11/image4-2.png)

I'm working on benches, so stand by for those

**Comment by Kixiron** [comment]
Unfortunately I don't think this can be implemented until [lol-html/#40](https://github.com/cloudflare/lol-html/issues/40) is upstreamed
