### ISSUE TITLE
Split up the README into webpages

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#888]
Currently the README is six screens long. We regularly have people asking questions in #docs-rs that are answered in the readme, and it's hard for me to find things even as the person who wrote most of it. We should split it up somehow; mdbook is markdown, simple, and we could host it ourselves on docs.rs (split up https://docs.rs/about/ as well? most of the content there is duplicated in the readme right now).

Inspired by https://github.com/rust-lang/rustup/issues/2396.

**Comment by jyn514** [comment]
This would also be a natural platform for #752

**Comment by Nemo157** [comment]
It might be possible to do this directly in our code instead of using mdbook, to avoid having to either check-in generated files or integrate mdbook into the build process.

As a quick sketch, we could define the table of contents via an enum, setup a `docs.rs/about/:page` handler that matches down to an enum variant, then `include_str!` a markdown file for each variant that gets rendered into a template that also includes a generated table of contents from the enum.

**Comment by jyn514** [comment]
Now that https://github.com/rust-lang/docs.rs/pull/924 is merged, I think we should remove most of the readme in favor of pointing to /about.

**Comment by Kixiron** [comment]
A lot of the forge can probably be deduplicated there as well
