### ISSUE TITLE
`delete version` doesn't remove the owner if there are no more releases with that owner

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#900]
See for example https://docs.rs/crate/pioneer/0.0.1 which still says it was authored by `@polygraphy`. This may need https://github.com/rust-lang/docs.rs/issues/766 to fix.

_Originally posted by @jyn514 in https://github.com/rust-lang/docs.rs/issues/837#issuecomment-660153609_

**Comment by Nemo157** [comment]
Ownership isn't linked to releases in any way, it's per-crate and mutable on crates.io. It just happens to only be updated from crates.io when we build a new release. We could add a `update-crates-io-data` to the CLI similar to the existing `update-github-fields` (though probably taking a crate name to update rather than updating all of them 🤣).

**Comment by jyn514** [comment]
Ah I hadn't considered that ownership can change at any time. Yeah in that case I think we should make this part of #766 .
