### ISSUE TITLE
My crate `async-proxy` fails to build in docs.rs

### ISSUE THREAD

**Issue by TonyGraim** [rust-lang/docs.rs#904]
**Crate name:** async-proxy
**Build failure link:** https://docs.rs/crate/async-proxy/0.2.3/builds

**Additional details:**
My crate `async-proxy` started failing to build when it crossed the version of 0.2.3

**Comment by Nemo157** [comment]
```
INFO] [stderr] error: proc-macro derive panicked
[INFO] [stderr]  --> /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/psl-0.4.1/src/list.rs:6:10
[INFO] [stderr]   |
[INFO] [stderr] 6 | #[derive(Psl, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default)]
[INFO] [stderr]   |          ^^^
[INFO] [stderr]   |
[INFO] [stderr]   = help: message: failed to download the list: failed to lookup address information: Temporary failure in name resolution
```

It appears the `Psl` derive attempts to use the network, this is blocked by the docs.rs build sandbox.

**Comment by Nemo157** [comment]
It appears there is an upstream issue for this: <https://github.com/addr-rs/addr/issues/6>

**Comment by antonok-edm** [comment]
This is a problem for the `adblock` crate as well, which also depends on `psl`. - https://docs.rs/crate/adblock/0.2.11

**Comment by Kixiron** [comment]
As Nemo said, `psl` (through `psl-lexer`) [accesses the internet](https://docs.rs/psl-lexer/0.2.0/src/psl_lexer/lib.rs.html#130) and this is impossible since docs.rs disallows network access to crates it's building for security reasons, but a solution would be to either use conditional compilation to disable the `psl` crates during docs.rs builds (Help with doing so can be found [here](https://docs.rs/about)) or to try and upstream changes to the `psl` crates that'll make them stop accessing the network in build steps on docs.rs

**Comment by jyn514** [comment]
I saw that 0.2.5 built successfully, so I'm going to close this issue. Feel free to re-open if you're still having trouble!
