### ISSUE TITLE
Header bar font is different on front page and rustdoc files

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#935]
Regression introduced in #930.

![rustdoc page](https://cdn.discordapp.com/attachments/541978667522195476/739862265586778222/unknown.png)
![home page](https://cdn.discordapp.com/attachments/541978667522195476/739862314337042552/unknown.png)

@Nemo157 suggested this is because the writer puts the navigation nested under `.rustdoc` and the style sets the `.rustdoc` font differently. We probably just need an override resetting the `nav-bar` font style to what's used for the rest of the body outside rustdoc.

**Comment by cynecx** [comment]
![Screenshot from 2020-08-18 17-08-03](https://user-images.githubusercontent.com/5961244/90530640-68915680-e175-11ea-9a21-a0a90fd74d7a.png)

Moving the "topbar" out of the tranformed rustdoc body should fix this (Hence using the correct font-family and not the overwritten one by the css class `div.rustdoc`). Tbh it doesn't make much sense to have the topbar in the rustdoc container since it has `position: fixed` anyway.

If this is the desired approach, I could open a PR.

**Comment by jyn514** [comment]
That sounds good to me! I think the way to implement this is by moving it from `templates/rustdoc/body.html` to `templates/rustdoc/head.html`.

**Comment by cynecx** [comment]
@jyn514 Mh. I don't think that's a good idea? That would put the `nav-container` div inside the `head` element which is not  a good idea (as I understand it is invalid HTML5). Afaict changes to https://github.com/rust-lang/docs.rs/blob/master/src/utils/html.rs are required, no?
