### ISSUE TITLE
Support for cargo-external-doc

### ISSUE THREAD

**Issue by mathstuf** [rust-lang/docs.rs#94]
The tool is [here](https://github.com/Geal/cargo-external-doc). It would be nice to have the extra docs supplied with a project built on docs.rs as well. Not sure of the best way to indicate that extra documentation is available though. A `Cargo.toml` flag?

**Comment by JelteF** [comment]
This would really be super great. Right now my package is missing most of its documentation. See the links in this section: https://docs.rs/derive_more/0.5.0/derive_more/#generated-code

**Comment by 9prady9** [comment]
Similar is the case with [arrayfire-rust](https://github.com/arrayfire/arrayfire-rust/issues/170) documentation. It doesn't generate the documentation from external markdown files and thus tutorial links in docs.rs are broken.

**Comment by jyn514** [comment]
I think this is out of scope for docs.rs. The supported way to do this is either `doc(include = "x.md")` (https://github.com/rust-lang/rust/issues/44732), which works today, or `doc = include_str!(...)` (soon to be merged in https://github.com/rust-lang/rust/pull/78837), which will probably end up replacing it.

docs.rs doesn't run doc-tests so that bit of the tool isn't relevant, and documenting examples is tracked in a separate issue: #238.

**Comment by mathstuf** [comment]
I haven't investigated/ported my projects yet, but `doc(include)` is probably sufficient for me at least.
